// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqxyqqupoifcxejykntn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeHlxcXVwb2lmY3hlanlrbnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTI0NzIsImV4cCI6MjA1NTU2ODQ3Mn0.ILs6RIvwORoBeLLxtfks_9HF1Zb_8XCM9KJUM9yPlIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);